version: '3.7'

services:
  config-server:
    image: "config-server:latest"
    container_name: config-server
    build: config-server
    ports:
      - "8888:8888"
    volumes: 
      - /home/hkoya/workspace/spring-boot-cloud-repository:/opt/git-repository
    environment: 
      - GIT_REPOSITORY=/opt/git-repository
  discovery:
    image: "discovery:latest"
    container_name: discovery
    build: discovery
    ports:
      - "8761:8761"
    environment: 
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    # depends_on: 
    #   - "config-server"
    # command: ["./wait-for-it.sh", "config-server:8888", "--", "discovery/bin/discovery"]
    command: ["./wait-for-health.sh", "-h", "http://config-server:8888/actuator/health", "-t", "30", "--", "discovery/bin/discovery"]
  producer:
    image: "producer:latest"
    container_name: producer
    build: producer
    ports:
      - "9091:9091"
    environment: 
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_BUS_ENABLED=false
      - EUREKA_CLIENT_SERVICE_URL=http://discovery:8761/eureka
    # depends_on:
    #   - "config-server"
    # command: ["./wait-for-it.sh", "config-server:8888", "--", "producer/bin/producer"]
    command: ["./wait-for-health.sh", "-h", "http://discovery:8761/actuator/health", "-t", "30", "--", "producer/bin/producer"]
  consumer:
    image: "consumer:latest"
    container_name: consumer
    build: consumer
    ports:
      - "9092:9092"
    environment: 
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL=http://discovery:8761/eureka      
    # depends_on: 
    #   - "config-server"
    # command: ["./wait-for-it.sh", "config-server:8888", "--", "consumer/bin/consumer"]
    command: ["./wait-for-health.sh", "-h", "http://discovery:8761/actuator/health", "-t", "30", "--", "consumer/bin/consumer"]
    