server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: config-server
      password: cs@123456
  cloud:
    config:
      server:
        git:
          uri: file://${GIT_REPOSITORY:${user.home}/workspace/git-repository/salesforce-config}
          cloneOnStart: true
          force-pull: true

#management:
#  security:
#    enabled: false
